import assert from 'node:assert/strict';
import { getBoardDefinition, getAbsolutePositionForBoard, isJumpPointForBoard, getOpponentForBoard } from './boardConfig.js';
const b = getBoardDefinition('classic4');
assert.equal(getAbsolutePositionForBoard(1, 0, b), 0);
assert.equal(getAbsolutePositionForBoard(1, 50, b), 50);
assert.equal(getAbsolutePositionForBoard(2, 1, b), 14);
assert.equal(getAbsolutePositionForBoard(2, 38, b), -3);
assert.equal(getAbsolutePositionForBoard(2, 39, b), -2);
assert.equal(getAbsolutePositionForBoard(2, 40, b), 1);
assert.equal(getAbsolutePositionForBoard(3, 25, b), -3);
assert.equal(getAbsolutePositionForBoard(3, 26, b), -2);
assert.equal(getAbsolutePositionForBoard(3, 27, b), 1);
assert.equal(getAbsolutePositionForBoard(4, 12, b), -3);
assert.equal(getAbsolutePositionForBoard(4, 13, b), -2);
assert.equal(getAbsolutePositionForBoard(4, 14, b), 1);
assert.equal(getAbsolutePositionForBoard(4, 1, b), 40);
assert.equal(getAbsolutePositionForBoard(2, 51, b), 51);
assert.equal(getOpponentForBoard(1, b), 3);
assert.equal(getOpponentForBoard(2, b), 4);
assert.equal(isJumpPointForBoard(2, b), true);
assert.equal(isJumpPointForBoard(6, b), true);
assert.equal(isJumpPointForBoard(50, b), false);
console.log('classic4 compatibility tests passed');
